### ISSUE TITLE
Scripts don't work (break dangerously) with filenames with spaces or wildcard literals

### ISSUE THREAD

**Issue by charles-dyfis-net** [Bandie/grub2-signing-extension#1]
Consider a file named `/boot/foo * .sig`.

The following code:

``` bash
for i in `find /boot -name "*.sig"` 
do
    rm $i
done
```

...will first run `rm /boot/foo`, then `rm *` (expanding the wildcard for the current directory), then `rm .sig`.

---

A safer way to write this would be:

``` bash
find /boot -name '*.sig' -exec rm -- '{}' +
```

...or, less efficiently (but demonstrating safely passing filenames from `find` into the shell in a manner that works correctly in all the corner cases -- names with literal backslashes, names with literal newlines, etc)...

``` bash
while IFS= read -r -d '' f; do
  rm -- "$f"
done < <(find /boot -name '*.sig' -print0)
```

---

Note the use of `--`; this is to ensure that subsequent arguments are treated as positional rather even if they might otherwise be evaluated as options, per <A HREF="http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02">POSIX Utility Syntax Guidelines #10</A>.

Similarly, for `find`, the `-exec ... {} +` usage <A HREF="http://pubs.opengroup.org/onlinepubs/009695399/utilities/find.html">can be found in the relevant POSIX specification</A>; the quoting of `{}` isn't needed for compliant shells, but can be required for zsh.

For `IFS= read -r -d ''`, the `-r` ensures that backslash literals are passed through unmodified; setting `IFS` to an empty string prevents whitespace from being trimmed from filenames; `-d ''` changes the record delimiter to a NUL byte (which is the only character which is guaranteed not to exist inside of a POSIX path). An in-depth discussion can be found in <A HREF="http://mywiki.wooledge.org/BashFAQ/001">BashFAQ #1</A>.

Using process substitution -- `<()` -- to generate a filename (typically, on Linux, of the form of `/dev/fd/##`) is a bashism which allows the loop to occur in the primary interpreter itself rather than in a subshell (as happens when piping into a loop in bash); see <A HREF="http://mywiki.wooledge.org/BashFAQ/024">BashFAQ #24</A>.

**Comment by Bandie** [comment]
Thanks for your contribution to make the script safer! :)
I just pushed the new `find -exec` way.

**Comment by charles-dyfis-net** [comment]
Glad to help! That one case was only an example -- there are still related issues elsewhere -- but I'd happy to fork and provide a PR for them if you'd prefer.

**Comment by Bandie** [comment]
Sure! :)
