### ISSUE TITLE
Issue with overwriting .sig and resigning .efi 

### ISSUE THREAD

**Issue by StarryTony** [Bandie/grub2-signing-extension#10]
Hi, thanks for your work. I am running Archlinux with UEFI secure mode. Currently I have two issues:
1. The script will generate *.sig files and try to overwrite them again for signing purpose. I have to answer yes for each overwriting individually otherwise it will create a new rename file for each *.sig.
2. As /boot/EFI/grub/*.efi has been signed for security boot mode, should the script exclude *.efi to avoid double signing?

**Comment by Bandie** [comment]
Hey,

1. Which script are you talking about?
2. I have barely experience in having EFI. If you say that this script should exclude them, we could do that.

**Comment by StarryTony** [comment]
Hi,
1. It’s the grub-sign scripts which sign all files in esp. But it also signs *.sig generated by itself and leads overwriting.
2. As .EFI have signatures signed by Microsoft to enable secure boot, resign could make their signatures be invalid.

Thank you.

On 2 Feb 2021, at 12:38, Bandie <notifications@github.com> wrote:

﻿

Hey,

  1.  Which script are you talking about?
  2.  I have barely experience in having EFI. If you say that this script should exclude them, we could do that.

**Comment by Bandie** [comment]
To 1.: This sounds like it couldn't delete the old signatures before creating the new ones.. Do you run it as root?
To 2.: I'll look into that then.

**Comment by StarryTony** [comment]
To 1.: Sure, I run as root. It prompts me to overwrite each .sig file (Y/N). No existing .sig file before running the script. I can see all existing .sig files are generated by the script. So they are not old?

Thank you.


On 2 Feb 2021, at 12:55, Bandie <notifications@github.com> wrote:

﻿

To 1.: This sounds like it couldn't delete the old signatures before creating the new ones.. Do you run it as root?
To 2.: I'll look into that then.

**Comment by Bandie** [comment]
hmh.. can you tell me which signature files exactly it tries to overwrite?

**Comment by StarryTony** [comment]
Hi, the script generates signatures for all files in esp. Therefore, it overwrites all .sig. For example, it generates a vmlinuz-linux.sig for vmlinuz-linux  and then overwrites itself.


On 2 Feb 2021, at 13:10, Bandie <notifications@github.com> wrote:

﻿

hmh.. can you tell me which signature files exactly it tries to overwrite?

**Comment by Bandie** [comment]
Right now `grub-sign` signs every file in /boot. This is a script you use only once per grub-install.
If you do kernel upgrades, one should run `grub-update-kernel-signature` as it removes /boot/*.sig and resigns it.

**Comment by StarryTony** [comment]
Hi,
Understand. But EFI are validated by shim as secure boot used. The validation chain looks like this: shim -> EFI -> Grub -> other grub files. I guess no need to re-sign EFI and Grub themselves. And most importantly, by removing an .efi file’s signature will prevent the computer boot from secure boot mode. Because EFI signatures have to be validated by UEFI boot loader.

The issue is that grub-sign signs everything without excluding EFI. But it’s a must to keep EFI’s signatures to be validated by shim.


On 6 Feb 2021, at 22:15, Bandie <notifications@github.com> wrote:

﻿

Right now grub-sign signs every file in /boot. This is a script you use only once per grub-install.
If you do kernel upgrades, one should run grub-update-kernel-signature as it removes /boot/*.sig and resigns it.
