### ISSUE TITLE
Unsafe Disposal of Digital Signatures

### ISSUE THREAD

**Issue by 5265644D61736F6E** [Bandie/grub2-signing-extension#11]
The `grub-unsign` command uses `rm` to dispose of outdated digital signatures. This is not a good practice for signatures that should not be used anymore. The `shred --remove=unlink` command might be better suited to dispose of the signatures.

A small problem with the `shred` command is that it uses the disk more than `rm`.

**Comment by Bandie** [comment]
Hey, I agree with that idea. I'll throw it in.

**Comment by Bandie** [comment]
Fixed in c7b049c
