### ISSUE TITLE
Request to tag and sign a release

### ISSUE THREAD

**Issue by craftyguy** [Bandie/grub2-signing-extension#3]
I would like to package this for Arch Linux's AUR. Normally I would just request the developer tag a release, but in this case I think it would be appropriate if you also signed the release package with your gpg key so that it can be verified when folks download/install it as a part of the AUR package.

Would you be able to do this? Thanks!

**Comment by Bandie** [comment]
Hi!
Thank you for wanting to package this project.
I tagged and signed it [here](https://github.com/Bandie/grub2-signing-extension/releases/tag/0.1). 

If you need something else, tell me. :)

**Comment by craftyguy** [comment]
Awesome, thank you!

It's now in AUR: https://aur.archlinux.org/packages/grub2-signing-extension/

**Comment by Bandie** [comment]
@craftyguy A new version has been released. I sent you something over the AUR form. :)

**Comment by craftyguy** [comment]
Cool, I'll update in AUR. FYI no need to re-open this issue each time, since I
get email notifications when the package in AUR is flagged out of date :)

**Comment by Bandie** [comment]
> FYI no need to re-open this issue each time
Alright, I just wanted to be sure.

Thank you very much! :)
