### ISSUE TITLE
own AUR package?

### ISSUE THREAD

**Issue by craftyguy** [Bandie/grub2-signing-extension#5]
@Bandie sorry I've been busy with other things and haven't had a chance to update the package in AUR. The script renaming will require some changes to the PKGBUILD, but nothing too extensive. Would you like to take over ownership of the package in AUR? If you don't want to (either because you don't want to or because you don't use Arch, or whatever reason), it's no problem.. I'll try to get to updating this package in the next few days. Sorry again for the delay..

**Comment by craftyguy** [comment]
Oh, I could make you a co-maintainer in AUR too :)

**Comment by Bandie** [comment]
Is oki! :) I updated it now :)
