### ISSUE TITLE
error : hash 'sha512' not loaded

### ISSUE THREAD

**Issue by bcHelix** [Bandie/grub2-signing-extension#6]
Just a quick FYI, when I initally followed the readme I got that error when booting and it dropped me into a `grub rescue` shell. I had to chroot, reinstall grub and then do `grub-install /dev/sda -k /root/pubkey --modules="gcry_sha256 gcry_dsa gcry_rsa gcry_sha512"` to make it work.

**Comment by Bandie** [comment]
Thanks, good to know! I'll put it into the README.md
